#!/usr/bin/env python3
"""
Create review contact sheets for:
1. each track observation, for false-positive review;
2. each provisional route-position candidate, for cross-pass comparison.

The input review CSV is generated by route_based_pipeline.py.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import cv2
import numpy as np
import pandas as pd


VIDEO_EXTENSIONS = {".mp4", ".mov", ".m4v", ".avi", ".mkv", ".webm"}


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--videos", required=True)
    parser.add_argument("--raw", required=True)
    parser.add_argument("--review", required=True, help="observation_review_template.csv")
    parser.add_argument("--output", default="route_review_gallery")
    return parser.parse_args()


def video_index(directory: Path):
    return {
        path.name: path
        for path in directory.rglob("*")
        if path.is_file() and path.suffix.lower() in VIDEO_EXTENSIONS
    }


def read_frame(video_path: Path, frame_number: int):
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        return None
    cap.set(cv2.CAP_PROP_POS_FRAMES, max(frame_number, 0))
    ok, frame = cap.read()
    cap.release()
    return frame if ok else None


def annotate(frame, row, title):
    output = frame.copy()
    x1, y1, x2, y2 = [
        int(round(float(row[column])))
        for column in ["x1", "y1", "x2", "y2"]
    ]
    cv2.rectangle(output, (x1, y1), (x2, y2), (0, 255, 255), 4)
    cv2.putText(
        output,
        title,
        (20, 42),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (255, 255, 255),
        3,
        cv2.LINE_AA,
    )
    cv2.putText(
        output,
        title,
        (20, 42),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (0, 0, 0),
        1,
        cv2.LINE_AA,
    )
    return output


def resize(frame, width=720):
    height, original_width = frame.shape[:2]
    scale = width / max(original_width, 1)
    return cv2.resize(frame, (width, int(round(height * scale))))


def sheet(panels, columns=2):
    panels = [resize(panel) for panel in panels]
    if not panels:
        return None
    max_h = max(panel.shape[0] for panel in panels)
    padded = []
    for panel in panels:
        if panel.shape[0] < max_h:
            panel = cv2.copyMakeBorder(
                panel, 0, max_h - panel.shape[0], 0, 0,
                cv2.BORDER_CONSTANT, value=(30, 30, 30)
            )
        padded.append(panel)

    rows = math.ceil(len(padded) / columns)
    blank = np.zeros_like(padded[0])
    while len(padded) < rows * columns:
        padded.append(blank.copy())

    return np.vstack([
        np.hstack(padded[row * columns:(row + 1) * columns])
        for row in range(rows)
    ])


def main():
    args = parse_args()
    output = Path(args.output)
    observation_dir = output / "observations"
    candidate_dir = output / "candidate_objects"
    observation_dir.mkdir(parents=True, exist_ok=True)
    candidate_dir.mkdir(parents=True, exist_ok=True)

    raw = pd.read_csv(args.raw)
    review = pd.read_csv(args.review)
    videos = video_index(Path(args.videos))

    representative_images = {}

    for item in review.itertuples(index=False):
        video = str(item.video)
        track_id = int(item.track_id)
        group = raw[
            (raw["video"] == video)
            & (raw["track_id"] == track_id)
        ].sort_values("frame")

        if group.empty or video not in videos:
            continue

        selected = [
            ("FIRST", group.iloc[0]),
            ("MIDDLE", group.iloc[len(group) // 2]),
            ("BEST", group.loc[
                ((group["x2"] - group["x1"]) * (group["y2"] - group["y1"])).idxmax()
            ]),
            ("LAST", group.iloc[-1]),
        ]

        panels = []
        best_panel = None

        for label, row in selected:
            frame = read_frame(videos[video], int(row["frame"]))
            if frame is None:
                continue
            title = (
                f"{label} | {item.observation_id} | {video} | "
                f"frame {int(row['frame'])}"
            )
            panel = annotate(frame, row, title)
            panels.append(panel)
            if label == "BEST":
                best_panel = panel

        contact = sheet(panels)
        if contact is not None:
            cv2.imwrite(
                str(observation_dir / f"{item.observation_id}.jpg"),
                contact,
            )

        if best_panel is not None:
            representative_images[item.observation_id] = best_panel

    for candidate_id, group in review.groupby("candidate_object_id"):
        panels = []
        for item in group.sort_values(["pass_id", "video"]).itertuples(index=False):
            panel = representative_images.get(item.observation_id)
            if panel is not None:
                panels.append(panel)

        contact = sheet(panels)
        if contact is not None:
            safe_id = str(candidate_id).replace("/", "_")
            cv2.imwrite(str(candidate_dir / f"{safe_id}.jpg"), contact)

    print(f"Gallery created: {output.resolve()}")


if __name__ == "__main__":
    main()
